require 'yaml'
require 'logger'
require 'erb'
require 'pry-byebug'
require 'typhoeus'
require 'nokogiri'
require 'open-uri'
require 'json'
require 'logger'
require 'fileutils'
require 'csv'

require_relative 'global_attributes'
